# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from officient_python_sdk import schemas  # noqa: F401


class ExpenseAddExpenseWithCategoryRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "category_id",
            "employee_id",
            "description",
        }
        
        class properties:
            description = schemas.StrSchema
            employee_id = schemas.Int32Schema
            category_id = schemas.Int32Schema
            amount = schemas.Float32Schema
            extra_information = schemas.StrSchema
            date = schemas.StrSchema
            filename = schemas.StrSchema
            file_base64 = schemas.StrSchema
        
            @staticmethod
            def dates() -> typing.Type['ExpenseAddExpenseWithCategoryRequestDates']:
                return ExpenseAddExpenseWithCategoryRequestDates
            distance = schemas.Int32Schema
            
            
            class ride(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "single": "SINGLE",
                        "double": "DOUBLE",
                    }
                
                @schemas.classproperty
                def SINGLE(cls):
                    return cls("single")
                
                @schemas.classproperty
                def DOUBLE(cls):
                    return cls("double")
            __annotations__ = {
                "description": description,
                "employee_id": employee_id,
                "category_id": category_id,
                "amount": amount,
                "extra_information": extra_information,
                "date": date,
                "filename": filename,
                "file_base64": file_base64,
                "dates": dates,
                "distance": distance,
                "ride": ride,
            }
    
    category_id: MetaOapg.properties.category_id
    employee_id: MetaOapg.properties.employee_id
    description: MetaOapg.properties.description
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee_id"]) -> MetaOapg.properties.employee_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["category_id"]) -> MetaOapg.properties.category_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extra_information"]) -> MetaOapg.properties.extra_information: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date"]) -> MetaOapg.properties.date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filename"]) -> MetaOapg.properties.filename: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file_base64"]) -> MetaOapg.properties.file_base64: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dates"]) -> 'ExpenseAddExpenseWithCategoryRequestDates': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["distance"]) -> MetaOapg.properties.distance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ride"]) -> MetaOapg.properties.ride: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "employee_id", "category_id", "amount", "extra_information", "date", "filename", "file_base64", "dates", "distance", "ride", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee_id"]) -> MetaOapg.properties.employee_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["category_id"]) -> MetaOapg.properties.category_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extra_information"]) -> typing.Union[MetaOapg.properties.extra_information, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date"]) -> typing.Union[MetaOapg.properties.date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filename"]) -> typing.Union[MetaOapg.properties.filename, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file_base64"]) -> typing.Union[MetaOapg.properties.file_base64, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dates"]) -> typing.Union['ExpenseAddExpenseWithCategoryRequestDates', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["distance"]) -> typing.Union[MetaOapg.properties.distance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ride"]) -> typing.Union[MetaOapg.properties.ride, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "employee_id", "category_id", "amount", "extra_information", "date", "filename", "file_base64", "dates", "distance", "ride", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        category_id: typing.Union[MetaOapg.properties.category_id, decimal.Decimal, int, ],
        employee_id: typing.Union[MetaOapg.properties.employee_id, decimal.Decimal, int, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        extra_information: typing.Union[MetaOapg.properties.extra_information, str, schemas.Unset] = schemas.unset,
        date: typing.Union[MetaOapg.properties.date, str, schemas.Unset] = schemas.unset,
        filename: typing.Union[MetaOapg.properties.filename, str, schemas.Unset] = schemas.unset,
        file_base64: typing.Union[MetaOapg.properties.file_base64, str, schemas.Unset] = schemas.unset,
        dates: typing.Union['ExpenseAddExpenseWithCategoryRequestDates', schemas.Unset] = schemas.unset,
        distance: typing.Union[MetaOapg.properties.distance, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        ride: typing.Union[MetaOapg.properties.ride, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ExpenseAddExpenseWithCategoryRequest':
        return super().__new__(
            cls,
            *args,
            category_id=category_id,
            employee_id=employee_id,
            description=description,
            amount=amount,
            extra_information=extra_information,
            date=date,
            filename=filename,
            file_base64=file_base64,
            dates=dates,
            distance=distance,
            ride=ride,
            _configuration=_configuration,
            **kwargs,
        )

from officient_python_sdk.model.expense_add_expense_with_category_request_dates import ExpenseAddExpenseWithCategoryRequestDates
