# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from officient_python_sdk import schemas  # noqa: F401


class ExpenseSetPayoutMethodAndStatusRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "new_payout_method",
        }
        
        class properties:
            
            
            class new_payout_method(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "UNDECIDED": "UNDECIDED",
                        "DO_NOT_PAYOUT": "DO_NOT_PAYOUT",
                        "PAYOUT_ACCOUNTING": "PAYOUT_ACCOUNTING",
                        "PAYOUT_OTHER": "PAYOUT_OTHER",
                        "PAYOUT_MANUALLY": "PAYOUT_MANUALLY",
                        "PAYOUT_USING_PAYROLL_PROVIDER": "PAYOUT_USING_PAYROLL_PROVIDER",
                    }
                
                @schemas.classproperty
                def UNDECIDED(cls):
                    return cls("UNDECIDED")
                
                @schemas.classproperty
                def DO_NOT_PAYOUT(cls):
                    return cls("DO_NOT_PAYOUT")
                
                @schemas.classproperty
                def PAYOUT_ACCOUNTING(cls):
                    return cls("PAYOUT_ACCOUNTING")
                
                @schemas.classproperty
                def PAYOUT_OTHER(cls):
                    return cls("PAYOUT_OTHER")
                
                @schemas.classproperty
                def PAYOUT_MANUALLY(cls):
                    return cls("PAYOUT_MANUALLY")
                
                @schemas.classproperty
                def PAYOUT_USING_PAYROLL_PROVIDER(cls):
                    return cls("PAYOUT_USING_PAYROLL_PROVIDER")
            payout_other_reason = schemas.StrSchema
            
            
            class payout_status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "PAID_OUT": "PAID_OUT",
                        "NOT_PAID_OUT": "NOT_PAID_OUT",
                    }
                
                @schemas.classproperty
                def PAID_OUT(cls):
                    return cls("PAID_OUT")
                
                @schemas.classproperty
                def NOT_PAID_OUT(cls):
                    return cls("NOT_PAID_OUT")
            period = schemas.StrSchema
            year = schemas.StrSchema
            __annotations__ = {
                "new_payout_method": new_payout_method,
                "payout_other_reason": payout_other_reason,
                "payout_status": payout_status,
                "period": period,
                "year": year,
            }
    
    new_payout_method: MetaOapg.properties.new_payout_method
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["new_payout_method"]) -> MetaOapg.properties.new_payout_method: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_other_reason"]) -> MetaOapg.properties.payout_other_reason: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_status"]) -> MetaOapg.properties.payout_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["period"]) -> MetaOapg.properties.period: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["year"]) -> MetaOapg.properties.year: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["new_payout_method", "payout_other_reason", "payout_status", "period", "year", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["new_payout_method"]) -> MetaOapg.properties.new_payout_method: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_other_reason"]) -> typing.Union[MetaOapg.properties.payout_other_reason, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_status"]) -> typing.Union[MetaOapg.properties.payout_status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["period"]) -> typing.Union[MetaOapg.properties.period, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["year"]) -> typing.Union[MetaOapg.properties.year, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["new_payout_method", "payout_other_reason", "payout_status", "period", "year", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        new_payout_method: typing.Union[MetaOapg.properties.new_payout_method, str, ],
        payout_other_reason: typing.Union[MetaOapg.properties.payout_other_reason, str, schemas.Unset] = schemas.unset,
        payout_status: typing.Union[MetaOapg.properties.payout_status, str, schemas.Unset] = schemas.unset,
        period: typing.Union[MetaOapg.properties.period, str, schemas.Unset] = schemas.unset,
        year: typing.Union[MetaOapg.properties.year, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ExpenseSetPayoutMethodAndStatusRequest':
        return super().__new__(
            cls,
            *args,
            new_payout_method=new_payout_method,
            payout_other_reason=payout_other_reason,
            payout_status=payout_status,
            period=period,
            year=year,
            _configuration=_configuration,
            **kwargs,
        )
