# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from officient_python_sdk import schemas  # noqa: F401


class ExpenseGetDetailResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            title = schemas.StrSchema
            description = schemas.StrSchema
            id = schemas.IntSchema
            employee_id = schemas.IntSchema
            date = schemas.StrSchema
            time_created = schemas.IntSchema
            status = schemas.StrSchema
            price = schemas.StrSchema
            file_id = schemas.IntSchema
            payout_method = schemas.StrSchema
            payout_period = schemas.AnyTypeSchema
            payout_period_frequency = schemas.AnyTypeSchema
            payout_year = schemas.AnyTypeSchema
            expense_category_id = schemas.IntSchema
            filename = schemas.AnyTypeSchema
            category_id = schemas.IntSchema
            category_name = schemas.StrSchema
            category_way_of_input = schemas.StrSchema
            price_per_kilometer = schemas.StrSchema
            distance = schemas.StrSchema
            request_id = schemas.AnyTypeSchema
            metadata = schemas.StrSchema
            dates = schemas.StrSchema
            date_approved = schemas.StrSchema
            payout_other_reason = schemas.StrSchema
            deleted = schemas.IntSchema
            payout_status = schemas.StrSchema
            date_created_dmy = schemas.StrSchema
            __annotations__ = {
                "title": title,
                "description": description,
                "id": id,
                "employee_id": employee_id,
                "date": date,
                "time_created": time_created,
                "status": status,
                "price": price,
                "file_id": file_id,
                "payout_method": payout_method,
                "payout_period": payout_period,
                "payout_period_frequency": payout_period_frequency,
                "payout_year": payout_year,
                "expense_category_id": expense_category_id,
                "filename": filename,
                "category_id": category_id,
                "category_name": category_name,
                "category_way_of_input": category_way_of_input,
                "price_per_kilometer": price_per_kilometer,
                "distance": distance,
                "request_id": request_id,
                "metadata": metadata,
                "dates": dates,
                "date_approved": date_approved,
                "payout_other_reason": payout_other_reason,
                "deleted": deleted,
                "payout_status": payout_status,
                "date_created_dmy": date_created_dmy,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee_id"]) -> MetaOapg.properties.employee_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date"]) -> MetaOapg.properties.date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["time_created"]) -> MetaOapg.properties.time_created: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price"]) -> MetaOapg.properties.price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file_id"]) -> MetaOapg.properties.file_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_method"]) -> MetaOapg.properties.payout_method: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_period"]) -> MetaOapg.properties.payout_period: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_period_frequency"]) -> MetaOapg.properties.payout_period_frequency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_year"]) -> MetaOapg.properties.payout_year: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expense_category_id"]) -> MetaOapg.properties.expense_category_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filename"]) -> MetaOapg.properties.filename: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["category_id"]) -> MetaOapg.properties.category_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["category_name"]) -> MetaOapg.properties.category_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["category_way_of_input"]) -> MetaOapg.properties.category_way_of_input: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price_per_kilometer"]) -> MetaOapg.properties.price_per_kilometer: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["distance"]) -> MetaOapg.properties.distance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["request_id"]) -> MetaOapg.properties.request_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dates"]) -> MetaOapg.properties.dates: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_approved"]) -> MetaOapg.properties.date_approved: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_other_reason"]) -> MetaOapg.properties.payout_other_reason: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deleted"]) -> MetaOapg.properties.deleted: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payout_status"]) -> MetaOapg.properties.payout_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_created_dmy"]) -> MetaOapg.properties.date_created_dmy: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "description", "id", "employee_id", "date", "time_created", "status", "price", "file_id", "payout_method", "payout_period", "payout_period_frequency", "payout_year", "expense_category_id", "filename", "category_id", "category_name", "category_way_of_input", "price_per_kilometer", "distance", "request_id", "metadata", "dates", "date_approved", "payout_other_reason", "deleted", "payout_status", "date_created_dmy", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee_id"]) -> typing.Union[MetaOapg.properties.employee_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date"]) -> typing.Union[MetaOapg.properties.date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["time_created"]) -> typing.Union[MetaOapg.properties.time_created, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price"]) -> typing.Union[MetaOapg.properties.price, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file_id"]) -> typing.Union[MetaOapg.properties.file_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_method"]) -> typing.Union[MetaOapg.properties.payout_method, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_period"]) -> typing.Union[MetaOapg.properties.payout_period, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_period_frequency"]) -> typing.Union[MetaOapg.properties.payout_period_frequency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_year"]) -> typing.Union[MetaOapg.properties.payout_year, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expense_category_id"]) -> typing.Union[MetaOapg.properties.expense_category_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filename"]) -> typing.Union[MetaOapg.properties.filename, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["category_id"]) -> typing.Union[MetaOapg.properties.category_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["category_name"]) -> typing.Union[MetaOapg.properties.category_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["category_way_of_input"]) -> typing.Union[MetaOapg.properties.category_way_of_input, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price_per_kilometer"]) -> typing.Union[MetaOapg.properties.price_per_kilometer, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["distance"]) -> typing.Union[MetaOapg.properties.distance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["request_id"]) -> typing.Union[MetaOapg.properties.request_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dates"]) -> typing.Union[MetaOapg.properties.dates, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_approved"]) -> typing.Union[MetaOapg.properties.date_approved, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_other_reason"]) -> typing.Union[MetaOapg.properties.payout_other_reason, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deleted"]) -> typing.Union[MetaOapg.properties.deleted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payout_status"]) -> typing.Union[MetaOapg.properties.payout_status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_created_dmy"]) -> typing.Union[MetaOapg.properties.date_created_dmy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "description", "id", "employee_id", "date", "time_created", "status", "price", "file_id", "payout_method", "payout_period", "payout_period_frequency", "payout_year", "expense_category_id", "filename", "category_id", "category_name", "category_way_of_input", "price_per_kilometer", "distance", "request_id", "metadata", "dates", "date_approved", "payout_other_reason", "deleted", "payout_status", "date_created_dmy", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        employee_id: typing.Union[MetaOapg.properties.employee_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        date: typing.Union[MetaOapg.properties.date, str, schemas.Unset] = schemas.unset,
        time_created: typing.Union[MetaOapg.properties.time_created, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        price: typing.Union[MetaOapg.properties.price, str, schemas.Unset] = schemas.unset,
        file_id: typing.Union[MetaOapg.properties.file_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        payout_method: typing.Union[MetaOapg.properties.payout_method, str, schemas.Unset] = schemas.unset,
        payout_period: typing.Union[MetaOapg.properties.payout_period, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        payout_period_frequency: typing.Union[MetaOapg.properties.payout_period_frequency, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        payout_year: typing.Union[MetaOapg.properties.payout_year, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        expense_category_id: typing.Union[MetaOapg.properties.expense_category_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        filename: typing.Union[MetaOapg.properties.filename, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        category_id: typing.Union[MetaOapg.properties.category_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        category_name: typing.Union[MetaOapg.properties.category_name, str, schemas.Unset] = schemas.unset,
        category_way_of_input: typing.Union[MetaOapg.properties.category_way_of_input, str, schemas.Unset] = schemas.unset,
        price_per_kilometer: typing.Union[MetaOapg.properties.price_per_kilometer, str, schemas.Unset] = schemas.unset,
        distance: typing.Union[MetaOapg.properties.distance, str, schemas.Unset] = schemas.unset,
        request_id: typing.Union[MetaOapg.properties.request_id, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, str, schemas.Unset] = schemas.unset,
        dates: typing.Union[MetaOapg.properties.dates, str, schemas.Unset] = schemas.unset,
        date_approved: typing.Union[MetaOapg.properties.date_approved, str, schemas.Unset] = schemas.unset,
        payout_other_reason: typing.Union[MetaOapg.properties.payout_other_reason, str, schemas.Unset] = schemas.unset,
        deleted: typing.Union[MetaOapg.properties.deleted, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        payout_status: typing.Union[MetaOapg.properties.payout_status, str, schemas.Unset] = schemas.unset,
        date_created_dmy: typing.Union[MetaOapg.properties.date_created_dmy, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ExpenseGetDetailResponseData':
        return super().__new__(
            cls,
            *args,
            title=title,
            description=description,
            id=id,
            employee_id=employee_id,
            date=date,
            time_created=time_created,
            status=status,
            price=price,
            file_id=file_id,
            payout_method=payout_method,
            payout_period=payout_period,
            payout_period_frequency=payout_period_frequency,
            payout_year=payout_year,
            expense_category_id=expense_category_id,
            filename=filename,
            category_id=category_id,
            category_name=category_name,
            category_way_of_input=category_way_of_input,
            price_per_kilometer=price_per_kilometer,
            distance=distance,
            request_id=request_id,
            metadata=metadata,
            dates=dates,
            date_approved=date_approved,
            payout_other_reason=payout_other_reason,
            deleted=deleted,
            payout_status=payout_status,
            date_created_dmy=date_created_dmy,
            _configuration=_configuration,
            **kwargs,
        )
