# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from officient_python_sdk import schemas  # noqa: F401


class PersonGetOneOffWageComponentsByMonthResponseComponentsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            description = schemas.StrSchema
            id = schemas.IntSchema
            code = schemas.StrSchema
            input_type = schemas.StrSchema
            type_id = schemas.IntSchema
            estimate_total = schemas.IntSchema
        
            @staticmethod
            def parts() -> typing.Type['PersonGetOneOffWageComponentsByMonthResponseComponentsItemParts']:
                return PersonGetOneOffWageComponentsByMonthResponseComponentsItemParts
            custom_payroll_data = schemas.AnyTypeSchema
            __annotations__ = {
                "description": description,
                "id": id,
                "code": code,
                "input_type": input_type,
                "type_id": type_id,
                "estimate_total": estimate_total,
                "parts": parts,
                "custom_payroll_data": custom_payroll_data,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["input_type"]) -> MetaOapg.properties.input_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type_id"]) -> MetaOapg.properties.type_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["estimate_total"]) -> MetaOapg.properties.estimate_total: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["parts"]) -> 'PersonGetOneOffWageComponentsByMonthResponseComponentsItemParts': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["custom_payroll_data"]) -> MetaOapg.properties.custom_payroll_data: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "id", "code", "input_type", "type_id", "estimate_total", "parts", "custom_payroll_data", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["input_type"]) -> typing.Union[MetaOapg.properties.input_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type_id"]) -> typing.Union[MetaOapg.properties.type_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["estimate_total"]) -> typing.Union[MetaOapg.properties.estimate_total, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["parts"]) -> typing.Union['PersonGetOneOffWageComponentsByMonthResponseComponentsItemParts', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["custom_payroll_data"]) -> typing.Union[MetaOapg.properties.custom_payroll_data, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "id", "code", "input_type", "type_id", "estimate_total", "parts", "custom_payroll_data", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        input_type: typing.Union[MetaOapg.properties.input_type, str, schemas.Unset] = schemas.unset,
        type_id: typing.Union[MetaOapg.properties.type_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        estimate_total: typing.Union[MetaOapg.properties.estimate_total, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        parts: typing.Union['PersonGetOneOffWageComponentsByMonthResponseComponentsItemParts', schemas.Unset] = schemas.unset,
        custom_payroll_data: typing.Union[MetaOapg.properties.custom_payroll_data, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PersonGetOneOffWageComponentsByMonthResponseComponentsItem':
        return super().__new__(
            cls,
            *args,
            description=description,
            id=id,
            code=code,
            input_type=input_type,
            type_id=type_id,
            estimate_total=estimate_total,
            parts=parts,
            custom_payroll_data=custom_payroll_data,
            _configuration=_configuration,
            **kwargs,
        )

from officient_python_sdk.model.person_get_one_off_wage_components_by_month_response_components_item_parts import PersonGetOneOffWageComponentsByMonthResponseComponentsItemParts
