# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExpenseGetDetailResponseData(TypedDict):
    pass

class OptionalExpenseGetDetailResponseData(TypedDict, total=False):
    title: str

    description: str

    id: int

    employee_id: int

    date: str

    time_created: int

    status: str

    price: str

    file_id: int

    payout_method: str

    payout_period: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    payout_period_frequency: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    payout_year: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    expense_category_id: int

    filename: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    category_id: int

    category_name: str

    category_way_of_input: str

    price_per_kilometer: str

    distance: str

    request_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    metadata: str

    dates: str

    date_approved: str

    payout_other_reason: str

    deleted: int

    payout_status: str

    date_created_dmy: str

class ExpenseGetDetailResponseData(RequiredExpenseGetDetailResponseData, OptionalExpenseGetDetailResponseData):
    pass
