# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExpenseListByMonthResponseDataItem(TypedDict):
    pass

class OptionalExpenseListByMonthResponseDataItem(TypedDict, total=False):
    title: str

    description: str

    id: int

    employee_id: int

    date: str

    time_created: int

    status: str

    price: str

    payout_method: str

    payout_period: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    payout_period_frequency: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    payout_year: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    expense_category_id: int

    price_per_kilometer: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    distance: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    metadata: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    dates: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    date_approved: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    payout_other_reason: str

    payout_status: str

class ExpenseListByMonthResponseDataItem(RequiredExpenseListByMonthResponseDataItem, OptionalExpenseListByMonthResponseDataItem):
    pass
