# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from officient_python_sdk.type.person_get_detail_response_data_address import PersonGetDetailResponseDataAddress
from officient_python_sdk.type.person_get_detail_response_data_current_reports_to import PersonGetDetailResponseDataCurrentReportsTo
from officient_python_sdk.type.person_get_detail_response_data_current_role import PersonGetDetailResponseDataCurrentRole
from officient_python_sdk.type.person_get_detail_response_data_custom_fields import PersonGetDetailResponseDataCustomFields
from officient_python_sdk.type.person_get_detail_response_data_emergency_contact import PersonGetDetailResponseDataEmergencyContact
from officient_python_sdk.type.person_get_detail_response_data_employment import PersonGetDetailResponseDataEmployment
from officient_python_sdk.type.person_get_detail_response_data_name_parts import PersonGetDetailResponseDataNameParts
from officient_python_sdk.type.person_get_detail_response_data_team import PersonGetDetailResponseDataTeam

class RequiredPersonGetDetailResponseData(TypedDict):
    pass

class OptionalPersonGetDetailResponseData(TypedDict, total=False):
    id: int

    deleted: int

    name: str

    first_name: str

    last_name: str

    created_at: int

    preferred_language_code: str

    email: str

    personal_email: str

    national_number: str

    social_security_nr: str

    birthdate: str

    birthplace: str

    avatar: str

    linked_payroll_provider: str

    linked_payroll_employee_id: str

    linked_payroll_employee_number: str

    dependent_adults_below_65: int

    dependent_children: int

    dependent_adults_above_65: int

    dependent_disabled_children: int

    dependent_disabled_adults_below_65: int

    dependent_disabled_adults_above_65: int

    spouse_has_income: bool

    phone: str

    civil_state: str

    nationality_country_code: str

    gender: str

    bank_account_iban: str

    bank_account_bic: str

    emergency_contact: PersonGetDetailResponseDataEmergencyContact

    address: PersonGetDetailResponseDataAddress

    team: PersonGetDetailResponseDataTeam

    employment: PersonGetDetailResponseDataEmployment

    current_role: PersonGetDetailResponseDataCurrentRole

    current_reports_to: PersonGetDetailResponseDataCurrentReportsTo

    custom_fields: PersonGetDetailResponseDataCustomFields

    name_parts: PersonGetDetailResponseDataNameParts

class PersonGetDetailResponseData(RequiredPersonGetDetailResponseData, OptionalPersonGetDetailResponseData):
    pass
