# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from officient_python_sdk.type.vehicle_get_detail_response_data_custom_fields import VehicleGetDetailResponseDataCustomFields
from officient_python_sdk.type.vehicle_get_detail_response_data_owner import VehicleGetDetailResponseDataOwner
from officient_python_sdk.type.vehicle_get_detail_response_data_yearly_cost import VehicleGetDetailResponseDataYearlyCost

class RequiredVehicleGetDetailResponseData(TypedDict):
    pass

class OptionalVehicleGetDetailResponseData(TypedDict, total=False):
    id: int

    type: str

    brand: str

    model: str

    fuel: str

    plate: str

    hp: int

    co2_g_km: int

    chassis_number: str

    color: str

    supplier: str

    contract_type: str

    catalogue_value: str

    date_first_registration: str

    specifics: str

    yearly_cost: VehicleGetDetailResponseDataYearlyCost

    deleted: int

    owner: VehicleGetDetailResponseDataOwner

    custom_fields: VehicleGetDetailResponseDataCustomFields

class VehicleGetDetailResponseData(RequiredVehicleGetDetailResponseData, OptionalVehicleGetDetailResponseData):
    pass
