# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AuthenticationGetAccessTokenRequest(BaseModel):
    # Authorization code in case of 3 legged oauth flow
    code: typing.Optional[str] = Field(None, alias='code')

    # client_id of your app. Can be found under 'my apps'
    client_id: typing.Optional[str] = Field(None, alias='client_id')

    # client secret of your app. Can be found under 'my apps'
    client_secret: typing.Optional[str] = Field(None, alias='client_secret')

    # should always be either authorization_code or refresh_token
    grant_type: typing.Optional[str] = Field(None, alias='grant_type')

    # optional
    refresh_token: typing.Optional[str] = Field(None, alias='refresh_token')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
