# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from officient_python_sdk.pydantic.person_get_detail_response_data_address import PersonGetDetailResponseDataAddress
from officient_python_sdk.pydantic.person_get_detail_response_data_current_reports_to import PersonGetDetailResponseDataCurrentReportsTo
from officient_python_sdk.pydantic.person_get_detail_response_data_current_role import PersonGetDetailResponseDataCurrentRole
from officient_python_sdk.pydantic.person_get_detail_response_data_custom_fields import PersonGetDetailResponseDataCustomFields
from officient_python_sdk.pydantic.person_get_detail_response_data_emergency_contact import PersonGetDetailResponseDataEmergencyContact
from officient_python_sdk.pydantic.person_get_detail_response_data_employment import PersonGetDetailResponseDataEmployment
from officient_python_sdk.pydantic.person_get_detail_response_data_name_parts import PersonGetDetailResponseDataNameParts
from officient_python_sdk.pydantic.person_get_detail_response_data_team import PersonGetDetailResponseDataTeam

class PersonGetDetailResponseData(BaseModel):
    id: typing.Optional[int] = Field(None, alias='id')

    deleted: typing.Optional[int] = Field(None, alias='deleted')

    name: typing.Optional[str] = Field(None, alias='name')

    first_name: typing.Optional[str] = Field(None, alias='first_name')

    last_name: typing.Optional[str] = Field(None, alias='last_name')

    created_at: typing.Optional[int] = Field(None, alias='created_at')

    preferred_language_code: typing.Optional[str] = Field(None, alias='preferred_language_code')

    email: typing.Optional[str] = Field(None, alias='email')

    personal_email: typing.Optional[str] = Field(None, alias='personal_email')

    national_number: typing.Optional[str] = Field(None, alias='national_number')

    social_security_nr: typing.Optional[str] = Field(None, alias='social_security_nr')

    birthdate: typing.Optional[str] = Field(None, alias='birthdate')

    birthplace: typing.Optional[str] = Field(None, alias='birthplace')

    avatar: typing.Optional[str] = Field(None, alias='avatar')

    linked_payroll_provider: typing.Optional[str] = Field(None, alias='linked_payroll_provider')

    linked_payroll_employee_id: typing.Optional[str] = Field(None, alias='linked_payroll_employee_id')

    linked_payroll_employee_number: typing.Optional[str] = Field(None, alias='linked_payroll_employee_number')

    dependent_adults_below_65: typing.Optional[int] = Field(None, alias='dependent_adults_below_65')

    dependent_children: typing.Optional[int] = Field(None, alias='dependent_children')

    dependent_adults_above_65: typing.Optional[int] = Field(None, alias='dependent_adults_above_65')

    dependent_disabled_children: typing.Optional[int] = Field(None, alias='dependent_disabled_children')

    dependent_disabled_adults_below_65: typing.Optional[int] = Field(None, alias='dependent_disabled_adults_below_65')

    dependent_disabled_adults_above_65: typing.Optional[int] = Field(None, alias='dependent_disabled_adults_above_65')

    spouse_has_income: typing.Optional[bool] = Field(None, alias='spouse_has_income')

    phone: typing.Optional[str] = Field(None, alias='phone')

    civil_state: typing.Optional[str] = Field(None, alias='civil_state')

    nationality_country_code: typing.Optional[str] = Field(None, alias='nationality_country_code')

    gender: typing.Optional[str] = Field(None, alias='gender')

    bank_account_iban: typing.Optional[str] = Field(None, alias='bank_account_iban')

    bank_account_bic: typing.Optional[str] = Field(None, alias='bank_account_bic')

    emergency_contact: typing.Optional[PersonGetDetailResponseDataEmergencyContact] = Field(None, alias='emergency_contact')

    address: typing.Optional[PersonGetDetailResponseDataAddress] = Field(None, alias='address')

    team: typing.Optional[PersonGetDetailResponseDataTeam] = Field(None, alias='team')

    employment: typing.Optional[PersonGetDetailResponseDataEmployment] = Field(None, alias='employment')

    current_role: typing.Optional[PersonGetDetailResponseDataCurrentRole] = Field(None, alias='current_role')

    current_reports_to: typing.Optional[PersonGetDetailResponseDataCurrentReportsTo] = Field(None, alias='current_reports_to')

    custom_fields: typing.Optional[PersonGetDetailResponseDataCustomFields] = Field(None, alias='custom_fields')

    name_parts: typing.Optional[PersonGetDetailResponseDataNameParts] = Field(None, alias='name_parts')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
