# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from officient_python_sdk.pydantic.vehicle_get_detail_response_data_custom_fields import VehicleGetDetailResponseDataCustomFields
from officient_python_sdk.pydantic.vehicle_get_detail_response_data_owner import VehicleGetDetailResponseDataOwner
from officient_python_sdk.pydantic.vehicle_get_detail_response_data_yearly_cost import VehicleGetDetailResponseDataYearlyCost

class VehicleGetDetailResponseData(BaseModel):
    id: typing.Optional[int] = Field(None, alias='id')

    type: typing.Optional[str] = Field(None, alias='type')

    brand: typing.Optional[str] = Field(None, alias='brand')

    model: typing.Optional[str] = Field(None, alias='model')

    fuel: typing.Optional[str] = Field(None, alias='fuel')

    plate: typing.Optional[str] = Field(None, alias='plate')

    hp: typing.Optional[int] = Field(None, alias='hp')

    co2_g_km: typing.Optional[int] = Field(None, alias='co2_g_km')

    chassis_number: typing.Optional[str] = Field(None, alias='chassis_number')

    color: typing.Optional[str] = Field(None, alias='color')

    supplier: typing.Optional[str] = Field(None, alias='supplier')

    contract_type: typing.Optional[str] = Field(None, alias='contract_type')

    catalogue_value: typing.Optional[str] = Field(None, alias='catalogue_value')

    date_first_registration: typing.Optional[str] = Field(None, alias='date_first_registration')

    specifics: typing.Optional[str] = Field(None, alias='specifics')

    yearly_cost: typing.Optional[VehicleGetDetailResponseDataYearlyCost] = Field(None, alias='yearly_cost')

    deleted: typing.Optional[int] = Field(None, alias='deleted')

    owner: typing.Optional[VehicleGetDetailResponseDataOwner] = Field(None, alias='owner')

    custom_fields: typing.Optional[VehicleGetDetailResponseDataCustomFields] = Field(None, alias='custom_fields')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
