# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import officient_python_sdk
from officient_python_sdk.model.expense_list_by_category_detail_response_data_payroll_components import ExpenseListByCategoryDetailResponseDataPayrollComponents
from officient_python_sdk import configuration


class TestExpenseListByCategoryDetailResponseDataPayrollComponents(unittest.TestCase):
    """ExpenseListByCategoryDetailResponseDataPayrollComponents unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
