# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from officient_python_sdk.paths._1_0_expenses_categories_add.post import AddCategory
from officient_python_sdk.paths._1_0_expenses_add.post import AddExpenseWithCategory
from officient_python_sdk.paths._1_0_expenses_expense_id.delete import DeleteById
from officient_python_sdk.paths._1_0_expenses_categories_category_id.delete import DeleteCategory
from officient_python_sdk.paths._1_0_expenses_categories_category_id.patch import EditCategoryName
from officient_python_sdk.paths._1_0_expenses_expense_id_detail.get import GetDetail
from officient_python_sdk.paths._1_0_expenses_categories_category_id_detail.get import ListByCategoryDetail
from officient_python_sdk.paths._1_0_expenses_list_year_month.get import ListByMonth
from officient_python_sdk.paths._1_0_expenses_list_year.get import ListByYear
from officient_python_sdk.paths._1_0_expenses_categories_list.get import ListCategories
from officient_python_sdk.paths._1_0_expenses_expense_id_update_payout.post import SetPayoutMethodAndStatus
from officient_python_sdk.paths._1_0_expenses_expense_id.patch import UpdateDetails
from officient_python_sdk.apis.tags.expense_api_raw import ExpenseApiRaw


class ExpenseApi(
    AddCategory,
    AddExpenseWithCategory,
    DeleteById,
    DeleteCategory,
    EditCategoryName,
    GetDetail,
    ListByCategoryDetail,
    ListByMonth,
    ListByYear,
    ListCategories,
    SetPayoutMethodAndStatus,
    UpdateDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ExpenseApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ExpenseApiRaw(api_client)
