# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from officient_python_sdk.paths._1_0_expenses_categories_add.post import AddCategoryRaw
from officient_python_sdk.paths._1_0_expenses_add.post import AddExpenseWithCategoryRaw
from officient_python_sdk.paths._1_0_expenses_expense_id.delete import DeleteByIdRaw
from officient_python_sdk.paths._1_0_expenses_categories_category_id.delete import DeleteCategoryRaw
from officient_python_sdk.paths._1_0_expenses_categories_category_id.patch import EditCategoryNameRaw
from officient_python_sdk.paths._1_0_expenses_expense_id_detail.get import GetDetailRaw
from officient_python_sdk.paths._1_0_expenses_categories_category_id_detail.get import ListByCategoryDetailRaw
from officient_python_sdk.paths._1_0_expenses_list_year_month.get import ListByMonthRaw
from officient_python_sdk.paths._1_0_expenses_list_year.get import ListByYearRaw
from officient_python_sdk.paths._1_0_expenses_categories_list.get import ListCategoriesRaw
from officient_python_sdk.paths._1_0_expenses_expense_id_update_payout.post import SetPayoutMethodAndStatusRaw
from officient_python_sdk.paths._1_0_expenses_expense_id.patch import UpdateDetailsRaw


class ExpenseApiRaw(
    AddCategoryRaw,
    AddExpenseWithCategoryRaw,
    DeleteByIdRaw,
    DeleteCategoryRaw,
    EditCategoryNameRaw,
    GetDetailRaw,
    ListByCategoryDetailRaw,
    ListByMonthRaw,
    ListByYearRaw,
    ListCategoriesRaw,
    SetPayoutMethodAndStatusRaw,
    UpdateDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
