# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from officient_python_sdk.paths._1_0_people_add.post import AddNew
from officient_python_sdk.paths._1_0_calendar_person_id_events_add.post import AddToCalendar
from officient_python_sdk.paths._1_0_calendar_person_id_priorityschemes_events_add.post import AddToCalendar0
from officient_python_sdk.paths._1_0_people_person_id_detail.patch import EditDetail
from officient_python_sdk.paths._1_0_budgets_people_person_id_year_list.get import GetBudgetsByYear
from officient_python_sdk.paths._1_0_wages_person_id_current.get import GetCurrentWage
from officient_python_sdk.paths._1_0_people_person_id_weekly_schedule_current.get import GetCurrentWeeklySchedule
from officient_python_sdk.paths._1_0_people_person_id_custom_fields.get import GetCustomFields
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day.get import GetDailyCalendar
from officient_python_sdk.paths._1_0_people_person_id_detail.get import GetDetail
from officient_python_sdk.paths._1_0_calendar_person_id_events_types_year_limits.get import GetEventTypeLimits
from officient_python_sdk.paths._1_0_people_person_id_manager.get import GetManagerDetails
from officient_python_sdk.paths._1_0_calendar_person_id_year_month.get import GetMonthlyCalendar
from officient_python_sdk.paths._1_0_wages_one_off_components_person_id_year_month_list.get import GetOneOffWageComponentsByMonth
from officient_python_sdk.paths._1_0_performance_reviews_person_id_list.get import GetPerformanceReviewsByPerson
from officient_python_sdk.paths._1_0_people_change_history.get import GetPersonalDataChanges
from officient_python_sdk.paths._1_0_calendar_person_id_verzuim_year.get import GetVerzuimPeriods
from officient_python_sdk.paths._1_0_wages_person_id_history.get import GetWageHistory
from officient_python_sdk.paths._1_0_calendar_person_id_year.get import GetYearlyCalendar
from officient_python_sdk.paths._1_0_wages_one_off_components_person_id_options_list.get import ListAvailableComponents
from officient_python_sdk.paths._1_0_budgets_people_person_id_budget_id_items_list.get import ListBudgetItems
from officient_python_sdk.paths._1_0_legal_dimonas_person_id_list.get import ListDimonasByPerson
from officient_python_sdk.paths._1_0_people_list.get import ListPeople
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day_events_set.put import OverwriteEvent
from officient_python_sdk.paths._1_0_calendar_person_id_events_event_id.delete import RemoveEvent
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day_work_reset.post import ResetTimeWorked
from officient_python_sdk.paths._1_0_people_search.get import SearchByCriteria
from officient_python_sdk.paths._1_0_people_person_id_role.put import SetFunctionDescription
from officient_python_sdk.paths._1_0_calendar_person_id_year_work_bulk.patch import UpdateBulkTimeWorked
from officient_python_sdk.paths._1_0_calendar_person_id_events_types_year_limits_type_id_set.post import UpdateEventTypeLimit
from officient_python_sdk.paths._1_0_people_person_id_manager.put import UpdateManager
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day_work.patch import UpdateTimeWorked
from officient_python_sdk.paths._1_0_people_person_id_photo.put import UploadAvatar
from officient_python_sdk.paths._1_0_roles_person_id_history.get import ViewRoleHistory
from officient_python_sdk.apis.tags.person_api_raw import PersonApiRaw


class PersonApi(
    AddNew,
    AddToCalendar,
    AddToCalendar0,
    EditDetail,
    GetBudgetsByYear,
    GetCurrentWage,
    GetCurrentWeeklySchedule,
    GetCustomFields,
    GetDailyCalendar,
    GetDetail,
    GetEventTypeLimits,
    GetManagerDetails,
    GetMonthlyCalendar,
    GetOneOffWageComponentsByMonth,
    GetPerformanceReviewsByPerson,
    GetPersonalDataChanges,
    GetVerzuimPeriods,
    GetWageHistory,
    GetYearlyCalendar,
    ListAvailableComponents,
    ListBudgetItems,
    ListDimonasByPerson,
    ListPeople,
    OverwriteEvent,
    RemoveEvent,
    ResetTimeWorked,
    SearchByCriteria,
    SetFunctionDescription,
    UpdateBulkTimeWorked,
    UpdateEventTypeLimit,
    UpdateManager,
    UpdateTimeWorked,
    UploadAvatar,
    ViewRoleHistory,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PersonApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PersonApiRaw(api_client)
