# coding: utf-8

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from officient_python_sdk.paths._1_0_people_add.post import AddNewRaw
from officient_python_sdk.paths._1_0_calendar_person_id_events_add.post import AddToCalendarRaw
from officient_python_sdk.paths._1_0_calendar_person_id_priorityschemes_events_add.post import AddToCalendar0Raw
from officient_python_sdk.paths._1_0_people_person_id_detail.patch import EditDetailRaw
from officient_python_sdk.paths._1_0_budgets_people_person_id_year_list.get import GetBudgetsByYearRaw
from officient_python_sdk.paths._1_0_wages_person_id_current.get import GetCurrentWageRaw
from officient_python_sdk.paths._1_0_people_person_id_weekly_schedule_current.get import GetCurrentWeeklyScheduleRaw
from officient_python_sdk.paths._1_0_people_person_id_custom_fields.get import GetCustomFieldsRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day.get import GetDailyCalendarRaw
from officient_python_sdk.paths._1_0_people_person_id_detail.get import GetDetailRaw
from officient_python_sdk.paths._1_0_calendar_person_id_events_types_year_limits.get import GetEventTypeLimitsRaw
from officient_python_sdk.paths._1_0_people_person_id_manager.get import GetManagerDetailsRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year_month.get import GetMonthlyCalendarRaw
from officient_python_sdk.paths._1_0_wages_one_off_components_person_id_year_month_list.get import GetOneOffWageComponentsByMonthRaw
from officient_python_sdk.paths._1_0_performance_reviews_person_id_list.get import GetPerformanceReviewsByPersonRaw
from officient_python_sdk.paths._1_0_people_change_history.get import GetPersonalDataChangesRaw
from officient_python_sdk.paths._1_0_calendar_person_id_verzuim_year.get import GetVerzuimPeriodsRaw
from officient_python_sdk.paths._1_0_wages_person_id_history.get import GetWageHistoryRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year.get import GetYearlyCalendarRaw
from officient_python_sdk.paths._1_0_wages_one_off_components_person_id_options_list.get import ListAvailableComponentsRaw
from officient_python_sdk.paths._1_0_budgets_people_person_id_budget_id_items_list.get import ListBudgetItemsRaw
from officient_python_sdk.paths._1_0_legal_dimonas_person_id_list.get import ListDimonasByPersonRaw
from officient_python_sdk.paths._1_0_people_list.get import ListPeopleRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day_events_set.put import OverwriteEventRaw
from officient_python_sdk.paths._1_0_calendar_person_id_events_event_id.delete import RemoveEventRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day_work_reset.post import ResetTimeWorkedRaw
from officient_python_sdk.paths._1_0_people_search.get import SearchByCriteriaRaw
from officient_python_sdk.paths._1_0_people_person_id_role.put import SetFunctionDescriptionRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year_work_bulk.patch import UpdateBulkTimeWorkedRaw
from officient_python_sdk.paths._1_0_calendar_person_id_events_types_year_limits_type_id_set.post import UpdateEventTypeLimitRaw
from officient_python_sdk.paths._1_0_people_person_id_manager.put import UpdateManagerRaw
from officient_python_sdk.paths._1_0_calendar_person_id_year_month_day_work.patch import UpdateTimeWorkedRaw
from officient_python_sdk.paths._1_0_people_person_id_photo.put import UploadAvatarRaw
from officient_python_sdk.paths._1_0_roles_person_id_history.get import ViewRoleHistoryRaw


class PersonApiRaw(
    AddNewRaw,
    AddToCalendarRaw,
    AddToCalendar0Raw,
    EditDetailRaw,
    GetBudgetsByYearRaw,
    GetCurrentWageRaw,
    GetCurrentWeeklyScheduleRaw,
    GetCustomFieldsRaw,
    GetDailyCalendarRaw,
    GetDetailRaw,
    GetEventTypeLimitsRaw,
    GetManagerDetailsRaw,
    GetMonthlyCalendarRaw,
    GetOneOffWageComponentsByMonthRaw,
    GetPerformanceReviewsByPersonRaw,
    GetPersonalDataChangesRaw,
    GetVerzuimPeriodsRaw,
    GetWageHistoryRaw,
    GetYearlyCalendarRaw,
    ListAvailableComponentsRaw,
    ListBudgetItemsRaw,
    ListDimonasByPersonRaw,
    ListPeopleRaw,
    OverwriteEventRaw,
    RemoveEventRaw,
    ResetTimeWorkedRaw,
    SearchByCriteriaRaw,
    SetFunctionDescriptionRaw,
    UpdateBulkTimeWorkedRaw,
    UpdateEventTypeLimitRaw,
    UpdateManagerRaw,
    UpdateTimeWorkedRaw,
    UploadAvatarRaw,
    ViewRoleHistoryRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
