# coding: utf-8

# flake8: noqa

"""
    Officient API

    Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0"

# import ApiClient
from officient_python_sdk.api_client import ApiClient

# import Configuration
from officient_python_sdk.configuration import Configuration

# import exceptions
from officient_python_sdk.exceptions import OpenApiException
from officient_python_sdk.exceptions import ApiAttributeError
from officient_python_sdk.exceptions import ApiTypeError
from officient_python_sdk.exceptions import ApiValueError
from officient_python_sdk.exceptions import ApiKeyError
from officient_python_sdk.exceptions import ApiException

from officient_python_sdk.client import Officient
